import { Roboto } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import SearchBar from "@/components/SearchBar/SearchBar";
import { ShowsProvider } from "@/context/MovieProvider";
import Logo from "@/public/logo.svg";
import Link from "next/link";
import { Analytics } from "../node_modules/@vercel/analytics/dist/react";

const roboto = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ShowsProvider>
          <header className="header">
            <Link href="/">
              <Image src={Logo} alt="logo" width="50" height="50" />
            </Link>
            <SearchBar />
          </header>
          <div className="container">{children}</div>
        </ShowsProvider>
        <Analytics />
      </body>
    </html>
  );
}
