import { Roboto } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar/SearchBar";
import { ShowsProvider } from "@/context/MovieProvider";

const roboto = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ShowsProvider>
          <header className="header">
            <SearchBar />
          </header>
          <div className="container">{children}</div>
        </ShowsProvider>
      </body>
    </html>
  );
}
